name: 'Run Unit Tests'
description: 'Runs unit tests on anaconda-opentelemetry package code'
inputs:
  node-version:
    description: 'Node version to use'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        shell: bash
        working-directory: .
        run: npm ci || npm install

      - name: Run TypeScript tests
        shell: bash
        working-directory: .
        run: npm run coverage
