name: 'Run Unit Tests'
description: 'Runs unit tests on anaconda-opentelemetry package code'
inputs:
  node-version:
    description: 'Node version to use'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        shell: bash
        working-directory: .
        run: npm ci || npm install

      - name: Run TypeScript tests
        shell: bash
        working-directory: .
        run: npm run coverage
