name: 'Run Integration Tests'
description: 'Runs integration tests on anaconda-opentelemetry package python code'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  otel-prod-token:
    description: 'OpenTelemetry production token'
    required: true
  otel-prod-endpoint:
    description: 'OpenTelemetry production endpoint'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        pip install pytest

    - name: Run integration tests
      shell: bash
      env:
        ATEL_DEFAULT_AUTH_TOKEN: ${{ inputs.otel-prod-token }}
        ATEL_DEFAULT_ENDPOINT: ${{ inputs.otel-prod-endpoint }}
      run: cd python && python -m pytest tests/integration_tests/test_external_prod_otel.py