name: Test & Deploy Cloudflare Workers

on:
  push:
    branches:
      - main

permissions: read-all

env:
  # The node version env here is used to determine cache keys for the caching of node_modules
  # as well as the actually installed version of node
  #
  # renovate: node-version
  node-version: 20.12.2

jobs:
  test-and-deploy:
    name: Cloudflare Worker - Heap Proxy
    runs-on:
      labels: self-hosted-amd64-small-privileged

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.node-version }}

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          path: approle-gha
          roleId: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          namespace: admin
          secrets: |
            cloud/common/data/cloudflare-api-keys/rate-limiter-worker account-id | CLOUDFLARE_ACCOUNT_ID ;
            cloud/common/data/cloudflare-api-keys/rate-limiter-worker token | CLOUDFLARE_API_TOKEN

      - name: Deploy prod
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          accountId: ${{ steps.import-secrets.outputs.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ steps.import-secrets.outputs.CLOUDFLARE_API_TOKEN }}
          workingDirectory: worker/
          command: deploy --env prod
