name: Publish TechDocs Site

on:
  push:
    branches: [main]
    paths:
    - docs/**
    - mkdocs.yml
    - .github/workflows/techdocs.yaml

jobs:
  publish-techdocs-site:
    runs-on: self-hosted-amd64-small-privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955   # v4.3.0

    - name: Publish TechDocs Site
      uses: anaconda/actions/.github/actions/publish-techdocs@main
      with:
        working-directory: ./docs
        entity-name: anaconda-opentelemetry